FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache curl docker-cli

COPY package*.json ./
COPY tsconfig.json ./
RUN npm install

COPY src ./src
RUN npm run build

EXPOSE 4001

CMD ["node", "dist/healer/index.js"]
