FROM node:20-alpine AS dashboard-build

WORKDIR /app
COPY dashboard/package*.json ./
RUN npm install
COPY dashboard ./
RUN npm run build

FROM caddy:2-alpine

COPY --from=dashboard-build /app/dist /srv
COPY Caddyfile /etc/caddy/Caddyfile
